Repository ombhojane/explainableai, pull requests merged in 2024-10, with the labels that each got.

#20 With contributing.md file
  Contributing.md
Labels: documentation, gssoc-ext, hacktoberfest, level1

#21 Updated core.py
  explainableai/core.py
Labels: good first issue, gssoc-ext, hacktoberfest, level1

#19 Issue #8
  explainableai/core.py
Labels: enhancement, gssoc-ext, hacktoberfest, level3

#29 Add Automated Greeting Workflow
  .github/workflows/greetings.yml
Labels: good first issue, feature request, gssoc-ext, hacktoberfest, level1

#39 Create user_guide.md
  explainableai/user_guide.md
Labels: documentation, good first issue, gssoc-ext, hacktoberfest, level1

#40 Updated API reference link
  README.md
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest, level1

#41 Implement logging throughout the package Labels #6
  createDB.py
  explainableai/__init__.py
  explainableai/anomaly_detection.py
  explainableai/core.py
  explainableai/fairness.py
  explainableai/feature_analysis.py
  explainableai/feature_engineering.py
  explainableai/feature_interaction.py
  explainableai/feature_selection.py
  explainableai/llm_explanations.py
  explainableai/model_comparison.py
  explainableai/model_evaluation.py
  explainableai/model_interpretability.py
  explainableai/model_selection.py
  explainableai/report_generator.py
  explainableai/utils.py
  explainableai/visualizations.py
  main.py
  tests/test_xai_wrapper.py
Labels: enhancement, gssoc-ext, hacktoberfest, level3

#54 Create issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest, level2

#55 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: good first issue, gssoc-ext, hacktoberfest, level1

#64 fix gitignore and readme
  README.md
Labels: documentation, gssoc-ext, hacktoberfest, level1

#62 Refactor main.py for improved logging and modularity
  main.py
Labels: good first issue, gssoc-ext, hacktoberfest, level1

#67 Added clear and consise comments to explaianble.ipynb
  notebooks/explaianble.ipynb
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest, level1

#87 Traffic Accident Prediction
  examples/Traffic Accident Prediction Model/README .md
  examples/Traffic Accident Prediction Model/Traffic Accident Prediction Model .ipynb
  examples/Traffic Accident Prediction Model/TrafficVision - Accident Prediction Model.png
Labels: good first issue, gssoc-ext, level3, hacktoberfest-accepted

#97 Create auto-comment-on-close.yml
  .github/workflows/auto-comment-on-close.yml
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#79 Updated module for handling large datsets
  explainableai/core.py
  requirements.txt
Labels: enhancement, gssoc-ext, level3, hacktoberfest-accepted

#105 Update .gitignore
  .gitignore
Labels: good first issue

#101 Create check_screenshot.yml
  .github/workflows/check_screenshot.yml
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#114 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: enhancement, gssoc-ext, level2, hacktoberfest-accepted

#115 ADD HACKTOBERFEST AND GSSOC BANNER ON THE README FILE
  Images/212284100-561aa473-3905-4a80-b561-0d28506553ee.gif
  Images/329829127-e79eb6de-81b1-4ffb-b6ed-f018bb977e88.png
  Images/Image
  Images/hacktober.png
  README.md
Labels: enhancement, good first issue, gssoc-ext, level1, hacktoberfest-accepted

#122 Github actions for more connectivity!
  .github/workflows/pr-checker.yaml
  .github/workflows/pr_merge_comment.yaml
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#120 Style Transfer with Neural Networks
  examples/Style Transfer with Neural Networks/README.md
  examples/Style Transfer with Neural Networks/Style Transfer with Neural Networks.ipynb
  examples/Style Transfer with Neural Networks/content image.jpg
  examples/Style Transfer with Neural Networks/style image.jpg
Labels: gssoc-ext, level2, hacktoberfest-accepted

#119 Explainable AI Integration for Time Series Model Interpretability
  examples/explainableai_time_series/Explainable AI Report.pdf
  examples/explainableai_time_series/explainableai_time_series.ipynb
  examples/explainableai_time_series/learning_curve.png
  examples/explainableai_time_series/lime_explanation.png
  examples/explainableai_time_series/partial_dependence.png
  examples/explainableai_time_series/real_sales_per_day.csv
  examples/explainableai_time_series/shap_summary.png
Labels: gssoc-ext, level2, hacktoberfest-accepted

#130 Enhance and Structure the Contributor Section
  README.md
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted
